# Generated by Django 3.2.9 on 2021-11-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snack',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='snack',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
